/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_interface;

import drivers.FileDriver;
import interpreter.abstract_syntax_tree.environment.GlobalError;
import interpreter.lexer.MusicLexer;
import interpreter.parser.MusicParser;
import java.io.File;
import java.io.IOException;
import java.io.StringReader;
import java.util.Arrays;
import java.util.LinkedList;
import javax.swing.JPanel;
import user_interface.text_editor.TextEditor;

/**
 *
 * @author zofia-px
 */
public class Player extends javax.swing.JFrame {
    private JPanel textEditorPanel;
    private TextEditor textEditorArea;
    private FileDriver fileDriver;
    private LinkedList<GlobalError> errors;
    private MusicLexer lexer;
    private MusicParser parser;
    
    
    /**
     * Creates new form Player
     */
    public Player() {
        this.errors = new LinkedList<>();
        this.fileDriver = new FileDriver();
        initComponents();
        initTextEditor();
        testing();
    }

    private void initTextEditor() {
        this.textEditorPanel = new JPanel();
        this.textEditorArea = new TextEditor(textEditorPanel, null);
        this.tabbedPanel.add("Editor de Texto", textEditorPanel);  
    }
    
    private void testing() {
        try {
            String input = fileDriver.readInputFile(new File("/home/zofia-px/Documents/ejemplo.txt"));
            this.lexer = new MusicLexer(new StringReader(input), errors);
            this.parser = new MusicParser(lexer, errors);
            this.parser.parse();
        } catch(IOException ex) {
            System.out.println(ex.getMessage() + "\n" + Arrays.toString(ex.getStackTrace()));
        } catch (Exception ex) {
            System.out.println(ex.getMessage() + "\n" + Arrays.toString(ex.getStackTrace()));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanel = new javax.swing.JTabbedPane();
        playerPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        reportMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1750, 1000));
        setPreferredSize(new java.awt.Dimension(1750, 1000));

        tabbedPanel.setBackground(new java.awt.Color(192, 214, 228));

        javax.swing.GroupLayout playerPanelLayout = new javax.swing.GroupLayout(playerPanel);
        playerPanel.setLayout(playerPanelLayout);
        playerPanelLayout.setHorizontalGroup(
            playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        playerPanelLayout.setVerticalGroup(
            playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        fileMenu.setText("File");
        menuBar.add(fileMenu);

        reportMenu.setText("Report");
        menuBar.add(reportMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
            .addComponent(playerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel playerPanel;
    private javax.swing.JMenu reportMenu;
    private javax.swing.JTabbedPane tabbedPanel;
    // End of variables declaration//GEN-END:variables
}
