
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package interpreter.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BOOL = 47;
  public static final int SOL8 = 83;
  public static final int REST = 20;
  public static final int EXT = 40;
  public static final int MI = 78;
  public static final int PLUSEQ = 15;
  public static final int MENSAJE = 72;
  public static final int SL = 38;
  public static final int ASC = 65;
  public static final int SI = 51;
  public static final int INDENT = 37;
  public static final int SOL = 82;
  public static final int CONT = 60;
  public static final int KEEP = 41;
  public static final int COMMA = 11;
  public static final int DEDENT = 36;
  public static final int SUM = 70;
  public static final int MENEQ = 30;
  public static final int ARR = 50;
  public static final int POT = 17;
  public static final int PRIMOS = 69;
  public static final int DOUBLE = 46;
  public static final int SI8 = 86;
  public static final int PISTA = 39;
  public static final int RR = 13;
  public static final int SAME = 35;
  public static final int FALSE = 43;
  public static final int NOT = 28;
  public static final int FA = 80;
  public static final int DEF = 55;
  public static final int NOR = 24;
  public static final int VAR = 44;
  public static final int LA = 84;
  public static final int RE = 76;
  public static final int EQ = 22;
  public static final int SALIR = 59;
  public static final int HACER = 58;
  public static final int PARA = 56;
  public static final int MOD = 16;
  public static final int MI8 = 79;
  public static final int ENTERO = 87;
  public static final int TRUE = 42;
  public static final int LONG = 71;
  public static final int PLUS = 21;
  public static final int DOBLE = 88;
  public static final int ORDER = 64;
  public static final int WHILE = 57;
  public static final int PAR = 67;
  public static final int CHAR = 48;
  public static final int SWITCH = 53;
  public static final int DO = 74;
  public static final int MAY = 33;
  public static final int DIV = 18;
  public static final int RETURN = 61;
  public static final int MULT = 19;
  public static final int PP = 14;
  public static final int INT = 45;
  public static final int NULO = 29;
  public static final int EOF = 0;
  public static final int SEMICOLON = 12;
  public static final int PC = 6;
  public static final int PA = 5;
  public static final int PLAY = 62;
  public static final int CARACTER = 2;
  public static final int PRINCIPAL = 73;
  public static final int DO8 = 75;
  public static final int OR = 25;
  public static final int error = 1;
  public static final int IMPAR = 68;
  public static final int LA8 = 85;
  public static final int MAYEQ = 31;
  public static final int CC = 10;
  public static final int CA = 9;
  public static final int DESC = 66;
  public static final int ID = 4;
  public static final int SINO = 52;
  public static final int CASE = 54;
  public static final int CADENA = 3;
  public static final int STRING = 49;
  public static final int LLC = 8;
  public static final int NEQ = 34;
  public static final int RE8 = 77;
  public static final int LLA = 7;
  public static final int AND = 27;
  public static final int WAIT = 63;
  public static final int FA8 = 81;
  public static final int MEN = 32;
  public static final int NAND = 26;
  public static final int XOR = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CARACTER",
  "CADENA",
  "ID",
  "PA",
  "PC",
  "LLA",
  "LLC",
  "CA",
  "CC",
  "COMMA",
  "SEMICOLON",
  "RR",
  "PP",
  "PLUSEQ",
  "MOD",
  "POT",
  "DIV",
  "MULT",
  "REST",
  "PLUS",
  "EQ",
  "XOR",
  "NOR",
  "OR",
  "NAND",
  "AND",
  "NOT",
  "NULO",
  "MENEQ",
  "MAYEQ",
  "MEN",
  "MAY",
  "NEQ",
  "SAME",
  "DEDENT",
  "INDENT",
  "SL",
  "PISTA",
  "EXT",
  "KEEP",
  "TRUE",
  "FALSE",
  "VAR",
  "INT",
  "DOUBLE",
  "BOOL",
  "CHAR",
  "STRING",
  "ARR",
  "SI",
  "SINO",
  "SWITCH",
  "CASE",
  "DEF",
  "PARA",
  "WHILE",
  "HACER",
  "SALIR",
  "CONT",
  "RETURN",
  "PLAY",
  "WAIT",
  "ORDER",
  "ASC",
  "DESC",
  "PAR",
  "IMPAR",
  "PRIMOS",
  "SUM",
  "LONG",
  "MENSAJE",
  "PRINCIPAL",
  "DO",
  "DO8",
  "RE",
  "RE8",
  "MI",
  "MI8",
  "FA",
  "FA8",
  "SOL",
  "SOL8",
  "LA",
  "LA8",
  "SI8",
  "ENTERO",
  "DOBLE"
  };
}

